language: cpp
script: bash -ex .travis-ci.sh
os:
  - linux
  - osx
compiler:
  - clang
env:
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 TEST_TARGETS=arm BAP_LOADER=llvm
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 TEST_TARGETS=x86 BAP_LOADER=llvm
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 TEST_TARGETS=x86_64 BAP_LOADER=llvm
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 TEST_TARGETS=arm BAP_LOADER=bap-elf
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 TEST_TARGETS=x86 BAP_LOADER=bap-elf
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 TEST_TARGETS=x86_64 BAP_LOADER=bap-elf
